apiVersion: config.vault.upbound.csm.volvocars.biz/v1alpha1
kind: InternalEntity
metadata:
  name: ie-b1129a71-c858-428d-ac91-38653aa612c1
  namespace: vault-crossplane
spec:
  parameters:
    commonConfig:
      deletionPolicy: Delete
      providerConfigRef: vault-provider-config
    internalEntity:
      name: ie-b1129a71-c858-428d-ac91-38653aa612c1
      objectId: b1129a71-c858-428d-ac91-38653aa612c1
      type: internal
