apiVersion: config.vault.upbound.csm.volvocars.biz/v1alpha1
kind: jwtAccessRequest
metadata:
  name: test
  namespace: vault-crossplane
  annotations:
    updatedBy: PDESHMUK@volvocars.com
spec:
  parameters:
    systemName: test
    managedIdentities:
    - b1129a71-c858-428d-ac91-38653aa612c2
    - b1129a71-c858-428d-ac91-38653aa612c1
    - 385e3e78-3d6e-4892-8a5c-a05bb2dc18e4
    readSecretPaths:
    - example/example/example
