apiVersion: apiextensions.crossplane.io/v1
kind: CompositeResourceDefinition
metadata:
  name: xkv2secretengines.config.vault.upbound.csm.volvocars.biz
  namespace: vault-crossplane
spec:
  group: config.vault.upbound.csm.volvocars.biz
  names:
    kind: XKv2SecretEngine
    plural: xkv2secretengines
  claimNames:
    kind: Kv2SecretEngine
    plural: kv2secretengines
  defaultCompositionRef:
    name: kv2secretengines.config.vault.upbound.csm.volvocars.biz
  versions:
    - name: v1alpha1
      served: true
      referenceable: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                resourceRef:
                  type: object
                  properties:
                    apiVersion:
                      type: string
                    kind:
                      type: string
                    name:
                      type: string
                    namespace:
                      type: string
                  required:
                    - apiVersion
                    - kind
                    - name
                parameters:
                  type: object
                  properties:
                    commonConfig:
                      description: Key-value map of common config.
                      type: object
                      properties:
                        deletionPolicy:
                          type: string
                          default: "Delete"
                          description: DeletionPolicy specifies what will happen to the underlying external resource when this managed resource is deleted - either "Delete" or "Orphan" the external resource.
                        providerConfigRef:
                          type: string
                          default: "vault-provider-config"
                          description: Crossplane vault provider to reference.
                    systemConfig:
                      description: Key-value map of the application/system config.
                      type: object
                      properties:
                        systemName:
                          type: string
                          description: The name of the application/system.
                        owner:
                          type: string
                          description: The Entra ID group that owns the system.
                        vaultEnvironment:
                          type: string
                          description: Vault environment where the secret engine is configured.
                      required:
                        - systemName
                        - owner
                        - vaultEnvironment
              required:
                - parameters