apiVersion: config.vault.upbound.csm.volvocars.biz/v1alpha1
kind: InternalGroup
metadata:
  name: {systemName}
  namespace: vault-crossplane
spec:
  parameters:
    commonConfig:
      deletionPolicy: "Delete"
      providerConfigRef: "vault-provider-config"
    group:
      name: {systemName}
      type: "internal"