name: Auto Approve Pull Request

on:
  pull_request:
    types: [opened]

jobs:
  approve:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Check if the PR is created by Claudiordev
        id: check_actor
        run: |
          if [[ "${{ github.actor }}" != "Claudiordev" ]]; then
            echo "The PR was not created by Claudiordev. Skipping auto-approval."
            exit 0  # Exit without errors if not from Claudiordev
          fi
          echo "The PR was created by Claudiordev. Proceeding with auto-approval."

      - name: Auto approve PR
        if: steps.check_actor.outputs.result == 'true'  # Only approve if the check passed
        uses: github-actions-approver@v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}